name: Bump Version

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'nuxbt/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'MANIFEST.in'
      - 'nfpm.yaml'
      - '.github/workflows/*'
      - 'debian/*'
      - '!debian/changelog'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v9.15.2
        with:
          github_token: ${{ github.token }}
